[package]
name = "linetime"
version = "0.1.0"
edition = "2021"
license = "MIT"
authors = ["Thomas Johannesson"]

[dependencies]
gumdrop = "0.8.1"

[dependencies.regex]
version = "1.11.1"
default-features = false
features = ["std", "perf"]
